name: gift_mobile_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.5.2
  flutter_svg: ^2.0.16
  path: ^1.8.3
  image_picker: ^1.1.2
  intl: ^0.20.2
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  group_button: ^5.3.4
  firebase_core: ^3.9.0
  firebase_auth: any
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.1.6
  http: ^1.3.0
  flutter_stripe: ^11.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_assets:
  assets_path: assets/
  output_path: lib/utils/constants/
  filename: app_assets.dart

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist-BlackItalic.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist-BoldItalic.ttf
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
        - asset: assets/fonts/Urbanist-ExtraBoldItalic.ttf
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
        - asset: assets/fonts/Urbanist-ExtraLightItalic.ttf
        - asset: assets/fonts/Urbanist-Italic.ttf
        - asset: assets/fonts/Urbanist-Light.ttf
        - asset: assets/fonts/Urbanist-LightItalic.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist-MediumItalic.ttf
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf
        - asset: assets/fonts/Urbanist-SemiBoldItalic.ttf
        - asset: assets/fonts/Urbanist-Thin.ttf
        - asset: assets/fonts/Urbanist-ThinItalic.ttf
          weight: 700
    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
