// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrZBnOcAMvohyfHP-5BbTIrIQYKeofBl4',
    appId: '1:53241063505:web:cf59e9fb368fa4593e7070',
    messagingSenderId: '53241063505',
    projectId: 'gift-faeb5',
    authDomain: 'gift-faeb5.firebaseapp.com',
    storageBucket: 'gift-faeb5.firebasestorage.app',
    measurementId: 'G-5NL7EBMXPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuJnlTeudN_1K38bZYXVw3db_KKMUXa0Q',
    appId: '1:53241063505:android:e27bf600d8960bb23e7070',
    messagingSenderId: '53241063505',
    projectId: 'gift-faeb5',
    storageBucket: 'gift-faeb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADaj0gyNtJEVMVFBNtDrflERccN7E-au8',
    appId: '1:53241063505:ios:5494b419acad50123e7070',
    messagingSenderId: '53241063505',
    projectId: 'gift-faeb5',
    storageBucket: 'gift-faeb5.firebasestorage.app',
    iosBundleId: 'com.example.gift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADaj0gyNtJEVMVFBNtDrflERccN7E-au8',
    appId: '1:53241063505:ios:5494b419acad50123e7070',
    messagingSenderId: '53241063505',
    projectId: 'gift-faeb5',
    storageBucket: 'gift-faeb5.firebasestorage.app',
    iosBundleId: 'com.example.gift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrZBnOcAMvohyfHP-5BbTIrIQYKeofBl4',
    appId: '1:53241063505:web:8c72be75fe2041ff3e7070',
    messagingSenderId: '53241063505',
    projectId: 'gift-faeb5',
    authDomain: 'gift-faeb5.firebaseapp.com',
    storageBucket: 'gift-faeb5.firebasestorage.app',
    measurementId: 'G-4S4T2WE4N7',
  );
}
